version : '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: circuit-search
    ports:
      - "8080:8080"
    depends_on:
      - solr
  solr:
    image: solr:9.6.1
    ports:
      - "8983:8983"
    volumes:
      - ./solr_data:/opt/solr/server/solr/first_core
    command: solr-precreate first_core